"""Canonical World Model v1 纯函数。"""

from __future__ import annotations

from typing import Any, Dict, Iterable, List, Optional

CANONICAL_WORLD_MODEL_ID = "worldfish.canonical_world.v1"
CANONICAL_WORLD_MODEL_VERSION = "1.0.0"

CANONICAL_SECTIONS = [
    "world_info",
    "settings",
    "entities",
    "events",
    "timelines",
    "maps",
    "rules",
    "references",
    "warnings",
]

_CONTEXT_ENTITY_LIMIT = 20
_CONTEXT_EVENT_LIMIT = 20
_CONTEXT_SETTING_LIMIT = 24
_CONTEXT_MAP_LIMIT = 8


def _is_mapping(value: Any) -> bool:
    return isinstance(value, dict)


def _get(value: Any, key: str, default: Any = None) -> Any:
    if isinstance(value, dict):
        return value.get(key, default)
    return getattr(value, key, default)


def _string(value: Any, default: str = "") -> str:
    if value is None:
        return default
    text = str(value).strip()
    return text if text else default


def _list(value: Any) -> List[Any]:
    if value is None:
        return []
    if isinstance(value, list):
        return value
    if isinstance(value, tuple):
        return list(value)
    return [value]


def _dict(value: Any) -> Dict[str, Any]:
    return value if isinstance(value, dict) else {}


def _to_plain_dict(value: Any) -> Dict[str, Any]:
    if isinstance(value, dict):
        return dict(value)
    if hasattr(value, "to_dict"):
        return dict(value.to_dict())
    if hasattr(value, "__dict__"):
        return dict(value.__dict__)
    return {}


def _unique_strings(values: Iterable[Any]) -> List[str]:
    seen = set()
    result: List[str] = []
    for value in values:
        text = _string(value)
        key = text.lower()
        if not key or key in seen:
            continue
        seen.add(key)
        result.append(text)
    return result


def _normalize_setting_item(item: Any) -> Optional[Dict[str, Any]]:
    raw = _to_plain_dict(item)
    name = _string(raw.get("name") or raw.get("title") or raw.get("label"))
    item_id = _string(raw.get("id"))
    setting_type = _string(raw.get("settingType") or raw.get("setting_type") or raw.get("type"), "setting")
    if setting_type not in {"setting", "collection"}:
        setting_type = "setting"
    if not name and not item_id:
        return None

    detail = _dict(raw.get("structuredDetail"))
    return {
        "id": item_id or f"setting:{name}",
        "name": name or item_id,
        "setting_type": setting_type,
        "category": _string(raw.get("category") or raw.get("type"), "other"),
        "collection_id": _string(raw.get("collectionId") or raw.get("collection_id")),
        "description": _string(raw.get("description") or raw.get("summary") or raw.get("content")),
        "detail": _string(raw.get("detailContent") or raw.get("detail") or detail.get("intro")),
        "aliases": _unique_strings(_list(raw.get("aliases") or raw.get("alias"))),
        "linked_entity_id": _string(raw.get("linkedEntityId") or raw.get("entityId")),
        "source_type": _string(raw.get("sourceType") or raw.get("source")),
        "auto_generated": bool(raw.get("autoGenerated", False)),
    }


def _normalize_entity(entity: Any) -> Optional[Dict[str, Any]]:
    raw = _to_plain_dict(entity)
    name = _string(raw.get("name"))
    entity_id = _string(raw.get("id"))
    if not name and not entity_id:
        return None

    attributes = _dict(raw.get("attributes"))
    relationships = [dict(item) for item in _list(raw.get("relationships") or raw.get("relations")) if isinstance(item, dict)]
    stages = [dict(item) for item in _list(raw.get("stages") or raw.get("阶段")) if isinstance(item, dict)]
    return {
        "id": entity_id or f"entity:{name}",
        "world_id": _string(raw.get("world_id")),
        "name": name or entity_id,
        "type": _string(raw.get("type"), "其他"),
        "aliases": _unique_strings(_list(raw.get("aliases") or raw.get("alias"))),
        "attributes": attributes,
        "relationships": relationships,
        "stages": stages,
        "setting_item_id": _string(raw.get("setting_item_id") or raw.get("settingId") or raw.get("linked_setting_id")),
        "evolution_refs": _unique_strings(_list(raw.get("evolution_refs"))),
        "created_at": _string(raw.get("created_at")),
    }


def _normalize_event(event: Any) -> Optional[Dict[str, Any]]:
    raw = _to_plain_dict(event)
    name = _string(raw.get("name") or raw.get("title"))
    event_id = _string(raw.get("id"))
    if not name and not event_id:
        return None

    return {
        "id": event_id or f"event:{name}",
        "world_id": _string(raw.get("world_id")),
        "name": name or event_id,
        "description": _string(raw.get("description") or raw.get("summary")),
        "date": _string(raw.get("date") or raw.get("time") or raw.get("timestamp")),
        "time_type": _string(raw.get("time_type"), "unknown"),
        "estimated_date": _string(raw.get("estimated_date"), "未知"),
        "entities": _unique_strings(_list(raw.get("entities") or raw.get("entity_ids"))),
        "created_at": _string(raw.get("created_at")),
    }


def _normalize_map_cell(cell: Any) -> Optional[Dict[str, Any]]:
    raw = _to_plain_dict(cell)
    cell_id = _string(raw.get("id"))
    name = _string(raw.get("name"))
    if not cell_id and not name:
        return None
    return {
        "id": cell_id or f"cell:{name}",
        "name": name,
        "q": raw.get("q", raw.get("x")),
        "r": raw.get("r", raw.get("y")),
        "terrain": _string(raw.get("terrain")),
        "status": _string(raw.get("status")),
        "faction": _string(raw.get("faction") or raw.get("owner")),
        "resources": _unique_strings(_list(raw.get("resources"))),
        "locations": _unique_strings(_list(raw.get("locations"))),
        "tags": _unique_strings(_list(raw.get("tags"))),
    }


def _normalize_map(item: Any) -> Optional[Dict[str, Any]]:
    raw = _to_plain_dict(item)
    map_id = _string(raw.get("id"))
    name = _string(raw.get("name"))
    if not map_id and not name:
        return None

    cells = [cell for cell in (_normalize_map_cell(cell) for cell in _list(raw.get("cells"))) if cell]
    notable_cells = [
        cell for cell in cells
        if cell.get("name")
        or cell.get("faction")
        or cell.get("resources")
        or (cell.get("status") or "") not in {"", "normal"}
    ]
    return {
        "id": map_id or f"map:{name}",
        "world_id": _string(raw.get("world_id")),
        "name": name or map_id,
        "description": _string(raw.get("description")),
        "type": _string(raw.get("type"), "world"),
        "grid_type": _string(raw.get("grid_type") or raw.get("gridType"), "hex"),
        "width": raw.get("width"),
        "height": raw.get("height"),
        "cell_count": len(cells),
        "notable_cells": notable_cells[:24],
        "layers": [dict(layer) for layer in _list(raw.get("layers")) if isinstance(layer, dict)],
    }


def _build_timelines(events: List[Dict[str, Any]], settings: Dict[str, Any]) -> List[Dict[str, Any]]:
    timelines: List[Dict[str, Any]] = []
    calendars = [dict(item) for item in _list(settings.get("calendars")) if isinstance(item, dict)]
    if calendars:
        timelines.append({
            "id": "timeline:calendars",
            "name": "历法与时间体系",
            "type": "calendar",
            "items": calendars,
        })
    dated_events = [event for event in events if event.get("date") or event.get("estimated_date")]
    if dated_events:
        timelines.append({
            "id": "timeline:events",
            "name": "关键事件时间线",
            "type": "events",
            "items": dated_events,
        })
    return timelines


def _build_rules(settings_items: List[Dict[str, Any]], world: Any) -> List[Dict[str, Any]]:
    rules: List[Dict[str, Any]] = []
    for item in settings_items:
        if item.get("setting_type") == "collection":
            continue
        category = _string(item.get("category")).lower()
        name = _string(item.get("name"))
        text = f"{name} {item.get('description') or ''} {item.get('detail') or ''}".lower()
        if category in {"ability", "rule", "rules", "system"} or any(keyword in text for keyword in ["规则", "法则", "体系", "魔法", "能力"]):
            rules.append(item)
    dnd_campaign = _get(world, "dnd_campaign")
    if isinstance(dnd_campaign, dict):
        rules.append({
            "id": "rule:dnd_campaign",
            "name": "DND 战役规则",
            "category": "trpg",
            "description": "DND 跑团模板中的战役规则配置",
            "detail": dnd_campaign,
        })
    return rules


def _build_references(world: Any, settings_items: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    references: List[Dict[str, Any]] = []
    reference_text = _string(_get(world, "reference_text"))
    if reference_text:
        references.append({
            "id": "reference:world.reference_text",
            "source": "world.reference_text",
            "title": "世界观参考文本",
            "text_preview": reference_text[:500],
            "char_count": len(reference_text),
        })
    for item in settings_items:
        source_type = _string(item.get("source_type"))
        if source_type:
            references.append({
                "id": f"reference:{item.get('id')}",
                "source": source_type,
                "title": item.get("name"),
                "target_id": item.get("id"),
            })
    return references


def validate_canonical_world(canonical: Dict[str, Any]) -> List[Dict[str, str]]:
    """校验 canonical world，返回警告而不是硬失败。"""

    warnings: List[Dict[str, str]] = []
    world_info = _dict(canonical.get("world_info"))
    if not _string(world_info.get("id")):
        warnings.append({"code": "missing_world_id", "message": "世界观缺少 id。"})
    if not _string(world_info.get("name")):
        warnings.append({"code": "missing_world_name", "message": "世界观缺少名称。"})
    if not canonical.get("entities"):
        warnings.append({"code": "empty_entities", "message": "世界观尚未包含实体。"})
    if not canonical.get("events"):
        warnings.append({"code": "empty_events", "message": "世界观尚未包含关键事件。"})
    if canonical.get("schema_version") != CANONICAL_WORLD_MODEL_VERSION:
        warnings.append({"code": "schema_version_mismatch", "message": "Canonical schema 版本与当前实现不一致。"})
    return warnings


def build_canonical_world(world: Any) -> Dict[str, Any]:
    """从现有 WorldSetting / dict 构建 Canonical World Model v1。"""

    settings = _dict(_get(world, "settings"))
    raw_items = settings.get("items") if isinstance(settings.get("items"), list) else []
    setting_items = [item for item in (_normalize_setting_item(item) for item in raw_items) if item]
    entities = [item for item in (_normalize_entity(item) for item in _list(_get(world, "entities"))) if item]
    events = [item for item in (_normalize_event(item) for item in _list(_get(world, "events"))) if item]

    map_data = _dict(settings.get("mapData"))
    structured_maps = map_data.get("structuredMaps") if isinstance(map_data.get("structuredMaps"), list) else []
    maps = [item for item in (_normalize_map(item) for item in structured_maps) if item]

    world_info = {
        "id": _string(_get(world, "id")),
        "name": _string(_get(world, "name")),
        "description": _string(_get(world, "description")),
        "era": _string(_get(world, "era")),
        "anchor_time": _string(_get(world, "anchor_time")),
        "writing_style": _string(_get(world, "writing_style")),
        "template_id": _string(_get(world, "template_id")),
        "template_name": _string(_get(world, "template_name")),
        "created_at": _string(_get(world, "created_at")),
        "updated_at": _string(_get(world, "updated_at")),
    }

    canonical: Dict[str, Any] = {
        "schema_id": CANONICAL_WORLD_MODEL_ID,
        "schema_version": CANONICAL_WORLD_MODEL_VERSION,
        "source_schema_version": _string(_get(world, "schema_version"), CANONICAL_WORLD_MODEL_VERSION),
        "sections": list(CANONICAL_SECTIONS),
        "world_info": world_info,
        "settings": {
            "items": setting_items,
            "collections": [item for item in setting_items if item.get("setting_type") == "collection"],
            "setting_count": len([item for item in setting_items if item.get("setting_type") == "setting"]),
            "collection_count": len([item for item in setting_items if item.get("setting_type") == "collection"]),
        },
        "entities": entities,
        "events": events,
        "timelines": _build_timelines(events, settings),
        "maps": {
            "items": maps,
            "map_count": len(maps),
            "region_relations": _string(map_data.get("regionRelations")),
            "country_relations": _string(map_data.get("countryRelations")),
            "important_locations": _string(map_data.get("importantLocations")),
        },
        "rules": [],
        "references": [],
        "warnings": [],
    }
    canonical["rules"] = _build_rules(setting_items, world)
    canonical["references"] = _build_references(world, setting_items)
    canonical["warnings"] = validate_canonical_world(canonical)
    return canonical


def summarize_canonical_world(canonical: Dict[str, Any]) -> Dict[str, Any]:
    """生成面向 RAG / 推演 / 报告 / TRPG 的稳定摘要。"""

    world_info = _dict(canonical.get("world_info"))
    settings = _dict(canonical.get("settings"))
    maps = _dict(canonical.get("maps"))
    entities = [item for item in _list(canonical.get("entities")) if isinstance(item, dict)]
    events = [item for item in _list(canonical.get("events")) if isinstance(item, dict)]
    setting_items = [item for item in _list(settings.get("items")) if isinstance(item, dict) and item.get("setting_type") == "setting"]
    map_items = [item for item in _list(maps.get("items")) if isinstance(item, dict)]

    lines: List[str] = []
    title = _string(world_info.get("name"), "未命名世界")
    lines.append(f"世界观：{title}")
    if world_info.get("description"):
        lines.append(f"简介：{world_info['description']}")
    if world_info.get("era"):
        lines.append(f"时代：{world_info['era']}")
    if world_info.get("anchor_time"):
        lines.append(f"锚定时间：{world_info['anchor_time']}")
    if entities:
        names = "、".join(item.get("name") or item.get("id") for item in entities[:_CONTEXT_ENTITY_LIMIT])
        lines.append(f"核心实体：{names}")
    if events:
        event_names = "、".join(item.get("name") or item.get("id") for item in events[:_CONTEXT_EVENT_LIMIT])
        lines.append(f"关键事件：{event_names}")
    if map_items:
        map_names = "、".join(item.get("name") or item.get("id") for item in map_items[:_CONTEXT_MAP_LIMIT])
        lines.append(f"地图：{map_names}")

    return {
        "title": title,
        "text": "\n".join(line for line in lines if line),
        "counts": {
            "entities": len(entities),
            "events": len(events),
            "settings": len(setting_items),
            "maps": len(map_items),
            "rules": len(_list(canonical.get("rules"))),
            "references": len(_list(canonical.get("references"))),
            "warnings": len(_list(canonical.get("warnings"))),
        },
        "entity_names": [item.get("name") for item in entities[:_CONTEXT_ENTITY_LIMIT] if item.get("name")],
        "event_names": [item.get("name") for item in events[:_CONTEXT_EVENT_LIMIT] if item.get("name")],
        "setting_names": [item.get("name") for item in setting_items[:_CONTEXT_SETTING_LIMIT] if item.get("name")],
    }
